### ISSUE TITLE
Auth (multiport): connector remains in plug_in_queue, although it is plugged out

### ISSUE THREAD

**Issue by FaHaGit** [EVerest/everest-core#567]
**Version:**
2024.2.0

**Module config:**

```
    config_module:
      connection_timeout: 20
      prioritize_authorization_over_stopping_transaction: true
      selection_algorithm: PlugEvents

    connections:
      evse_manager:
        - module_id: connector_1
          implementation_id: evse
        - module_id: connector_2
          implementation_id: evse
```

**Describe the problem:**

In case when a plug is plugged-in and plugged-out without performing an authorization via RFID, the connector remains in the plug_in_queue although it has already been unplugged. As a result, the plug-selection-algorithm, bases on "PlugEvents", detects the unplugged connector and authorize it for charging when a RFID card is presented, without any plugged-in connectors.

**How to reproduce:**

1. In a setup for a Multi-port charger, plug in one of the connectors, without authorziation (Plug in before authoziation).
2. Plug the connector out, also without authoziation.
3. Swipe a RFID card. The authoziation will be assigned to the connector which was just plugged out.

**Expectation:**
The authoziation should not be assigned to any connector until one of them is plugged in.

**Describe your solution:**

Remove connector ID from list in case "SessionFinished" event has been received

**Additional context:**

--
