### ISSUE TITLE
EvseV2G can not encode ServiceDiscoveryRes if both payment options are disabled

### ISSUE THREAD

**Issue by SebaLukas** [EVerest/everest-core#596]
### Describe the bug

If in the config both payment options are disabled, then the EvseV2G module can not encode the ServiceDiscoveryRes message. Because no payment is provided.

### EVerest Domain

ISO15118

### Affected EVerest Module

EvseV2G

### To Reproduce

```
evse_manager:
    module: EvseManager
    config_module:
      payment_enable_contract: false
      payment_enable_eim: false
```
